name: GitlabSync

on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Sync with target repository
        uses: jordansiegel/rej_git_repo_sync@v0.1.0
        with:
          target-url: ${{ secrets.TARGET_URL }}
          target-username: ${{ secrets.TARGET_USERNAME }}
          target-token: ${{ secrets.TARGET_TOKEN }}
      
      - name: Push to GitLab
        run: |
          git remote add target ${{ secrets.TARGET_URL }}
          git push --mirror target
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
